version: 2

sources:
  - name: "{{ env_var('TARGET_BIGQUERY_DATASET_ID') }}"
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('TARGET_BIGQUERY_DATASET_ID_DB') }}"
    tables:
      - name: olist_customers_dataset
      - name: olist_orders_dataset
      - name: olist_order_items_dataset
      - name: olist_order_payments_dataset
      - name: olist_order_reviews_dataset
      - name: olist_products_dataset
      - name: olist_sellers_dataset
      - name: olist_geolocation_dataset
      - name: olist_marketing_qualified_leads_dataset
      - name: olist_closed_deals_dataset
      - name: product_category_name_translation