version: 2

models:
  - name: delivery_performance
    description: Delivery performance model showing delivery days, delay days, late delivery flag and review score.
    columns:
      - name: order_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: review_score
        tests:
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
                quote: false

  - name: customer_segmentation
    description: Customer segmentation model based on total customer spending.
    columns:
      - name: customer_unique_id
        tests:
          - not_null
      - name: customer_segment
        tests:
          - accepted_values:
              arguments:
                values: ['Gold', 'Silver', 'Bronze']

  - name: seller_scorecard
    description: Seller scorecard model showing seller revenue, order count and average review score.
    columns:
      - name: seller_id
        tests:
          - not_null