name: 'olist_dbt'
version: '1.0.0'
config-version: 2

profile: 'olist_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Folder-level materialization rules
models:
  olist_dbt:
    # 1. Main models/ folder default: Materializes your Fact tables as Tables
    +materialized: table
       
    # 2. Star Schema Subfolder: Explicitly targets your Dimension tables as Tables
    star:
      +materialized: table